services:
  mariadb:
    image: mariadb:11.4
    container_name: svetlana-mariadb
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    #healthcheck:
      #test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      #interval: 10s
      #timeout: 5s
      #retries: 5
    #environment:
      #MYSQL_ROOT_PASSWORD: your_secure_password
      #MYSQL_DATABASE: my_app
    #ports:
      #- "3307:3306" # Connect via 3307 to stay away from XAMPP!
volumes:
  mariadb_data: